name: deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: |
          実行する環境
          dev / prod のいずれか
    secrets:
      credential:
        required: true
        description: |
          GOOGLE_APPLICATION_CREDENTIALSのjsonの値を入れる

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [16]
    env:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
      GCLOUD_SERVICE_KEY: ${{ secrets.credential }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache firebase emulators
      uses: actions/cache@v3
      with:
        path: ~/.cache/firebase/emulators
        key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ matrix.os }}-node-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: install dependencies
      run: yarn install
    - name: run build
      run: |
        yarn build:common
        yarn workspace @firebase-monorepo-template/web build:${{ inputs.environment }}
    - run: echo $GCLOUD_SERVICE_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
    - run: yarn deploy:${{ inputs.environment }}
    - name: delete GOOGLE_APPLICATION_CREDENTIALS
      run: rm $GOOGLE_APPLICATION_CREDENTIALS
      if: ${{ always() }}

