name: deploy dev

on:
  push:
    branches:
      - develop

jobs:

  deploy-prod:
    uses: virapture/firebase-monorepo-template/.github/workflows/deploy.yml@develop
    with:
      environment: dev
    secrets:
      credential: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DEV }}
